[server]
headless = true
port = 8502
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF3E93"
backgroundColor = "#FFFDFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#181316"
font = "sans serif"
